### ISSUE TITLE
My bad😂 plz finish it

### ISSUE THREAD

**Issue by TheUtopianPlayz** [provsalt/CrossOnlineCount#4]
Lol the last issue was a typo, I do want u to finish this plugin😂 my bad

**Comment by provsalt** [comment]
> Lol the last issue was a typo, I do want u to finish this plugin my bad

![Screenshot_2020-01-20-20-30-52-88_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/39023494/72726657-c5497600-3b80-11ea-88c2-0b07dd16b0fd.png)
No entited brat
